WebApplication1/Models/compagny.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class compagny
    {
        public int id { get; set; }
        public string name { get; set; }
        public string adress { get; set; }


        public List<Contact> contacts { get; set; } = new List<Contact>();
    }


    
   
}

WebApplication1/Controllers/CompagnyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.BDD;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CompagnyController : Controller
    {
        public ActionResult Details(int ID)
        {
            foreach(var compagnie in Repository.listCompagny)
            {
                if (compagnie.id == ID)
                {
                    return View(compagnie);
                }
                
            }
            return null;
        }
        // GET: Compagny
        public ActionResult Index()
        {
            using (var context = new Mycontext())
            {
                var movies = context.Movies.ToList();
                //return View(movies);

            }
            return View(Repository.listCompagny);
        }

        public ActionResult CreateLogin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateLogin(Login l)
        {
            using (var context = new Mycontext())
            {
                var login = context.Login.Add(l);
                context.SaveChanges();
                return View("Sucess");
            }
        }
        [HttpGet]
        public ActionResult Update(int Id)
        {
            var compagnie = Repository.getCompagnyByID(Id);
            return View(compagnie);
        }
        [HttpPost]
        public ActionResult Update(compagny c)
        {
            var compagnie = Repository.getCompagnyByID(c.id);
            compagnie.name = c.name;
            compagnie.adress = c.adress;
            return RedirectToAction("Details", new {id = c.id});
        }
       
        [HttpPost]
        public ActionResult Delete(int Id)
        {
            var compagnie = Repository.getCompagnyByID(Id);
            Repository.listCompagny.Remove(compagnie);
            return RedirectToAction("Index");
        }
    }
}

WebApplication1/Views/Compagny/Create.cshtml
@model WebApplication1.Models.compagny
@{
    ViewBag.Title = "Create";
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
   
</head>
<body>
    <link href="projetfin.css" rel="stylesheet" type="text/css" media="all" />
    <h1>Ajout de contacts</h1>
        <h2>
            <form action="create" method="post">
                <p>Adress <input class="entreText" type="text" name="Adress" /></p>
                <p>Compagny <input class="entreText" type="text" name="Name" /></p>
                <input class="bouton" type="submit" value="Valider" />
            </form>
        </h2>
</body>
</html>

WebApplication1/Views/Compagny/CreateLogin.cshtml
@model WebApplication1.Models.login
@{
    ViewBag.Title = "CreateContact";
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
   
</head>
<body>
    <link href="projetfin.css" rel="stylesheet" type="text/css" media="all" />
    <h1 style="text-align:center; color:white">Register</h1>
        <h2 style="text-align:center; color:white">            
            @using (Html.BeginForm("createLogin", "Compagny", FormMethod.Post, new { encType = "multipart/form-data" }))
            {
                <p>Login <input class="entreText" type="text" name="Login" /></p>
                <input type="submit" value="Add" name="submitme" id="submitme" />
            }
        </h2>
</body>
</html>

WebApplication1/Views/Compagny/Details.cshtml
@model WebApplication1.Models.compagny
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
    <p>
        @Model.adress
        @Model.id
        @Model.name



        @foreach(var Contact in Model.contacts)
        {
           <div> @Contact.name</div>
           <div>@Contact.number</div> 
           <div>@Contact.id</div> 
        }
    </p>
    <p>
        <a href="\Compagny/update/@Model.id">Modify Compagny ?</a>
    </p>

WebApplication1/Views/Compagny/Index.cshtml
@model IEnumerable<WebApplication1.Models.compagny>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

   @foreach (var item in Model)
   {
    <p>
        @item.name
    </p>
    <p>
        <a href="\Compagny/Details/@item.id" rel="stylesheet" media="all" >Details </a>
        <input class="btn" onclick="javascript:myFunction()" type="submit" value="Delete "name="Delete" />

<script>
function myFunction() {
    var r = confirm("Are you sure ?");
    if (r==true)
        {
        var http =new   XMLHttpRequest();
        var url = "\Compagny/Delete/@item.id";
        http.open("POST", url, true);

        //Send the proper header information along with the request
        http.setRequestHeader("Content-type", "application/x-www-form-urlencoded");

        http.onreadystatechange = function() {//Call a function when the state changes.
    if(http.readyState == 4 && http.status == 200) {
        location.reload();
        }
    }
    http.send();
    }

}
</script>
</p>


   }
    <p></p>
    <p><a href="\Compagny/create">Create Compagny ?</a></p>
    
    

WebApplication1/Views/Compagny/Sucess.cshtml
@model WebApplication1.Models.login
@{
    ViewBag.Title = "Sucess";
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />

</head>
<body style="text-align:center; color:white; font-size:25px">
    <link href="projetfin.css" rel="stylesheet" type="text/css" media="all" />
    <p>Well done ! Your profile has been sucessfully created !</p>
    <p>Do you want to go to the HomePage ? <a href="\Home" > Yes </a></p>
</body>
</html>

WebApplication1/Views/Compagny/Update.cshtml
@model WebApplication1.Models.compagny
@{
    ViewBag.Title = "Update";
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />

</head>
<body>
    <link href="projet.css" rel="stylesheet" type="text/css" media="all" />
    <h1>Ajout de d'entreprise</h1>
    <h2>
        <form action="update" method="post">
            <p><input type="hidden" value="@Model.id"name="Id" /></p>
            <p>Adress <input class="entreText" value="@Model.adress" type="text" name="Adress" /></p>
            <p>Compagny <input class="entreText" value="@Model.name" type="text" name="Name" /></p>
            <input class="bouton" type="submit" value="Valider" />
        </form>
    </h2>
</body>
</html>